### ISSUE TITLE
Can I change the location of the Review Source Folder

### ISSUE THREAD

**Issue by StuartBrown1981** [AgileReview-Project/AgileReview-Legacy-Plugin#17]
Currently Agile Review will create the Review Source Project folder under the workspace directory for the eclipse project.  Is it possible to alter the location to another directory so I can capture it under the source control of the project?  If not could this be an enhancement?

The reason I ask is that our version control in in sync with a directory outside the workspace and so it will not be bale to add review .xml files generated after a review.

**Comment by postmann** [comment]
Hi StuartBrown1981,

I just tried it out with git. I create a SourceFolder within my current workspace, then moved the project folder from the workspace to a different location and re-imported it. Although this is only a workaround it works fine.

Is this sufficient for you?

Regards,
Peter

**Comment by StuartBrown1981** [comment]
Hi Peter,

Your suggestion worked when using mercurial although I had to set up a project folder to import the .project file back into - it could not import back into the version control root directory without specifying an import directory.

Many thanks

Stuart
