### ISSUE TITLE
 whitespace between code and agile comment was still there when run project cleanup

### ISSUE THREAD

**Issue by Pnalson** [AgileReview-Project/AgileReview-Legacy-Plugin#25]
I noticed that  AgileReview 0.9.2 add a whitespace between code and agile comment, but when I run the project cleanup the whiteapace was still there.

**Comment by maybeec** [comment]
Hi, can you provide an example?

**Comment by Pnalson** [comment]
1. origin review file
![image](https://user-images.githubusercontent.com/18171453/40212291-dbc4a292-5a81-11e8-8b19-d9de6d1f6438.png)

2. add a comment
![image](https://user-images.githubusercontent.com/18171453/40212131-01b87d08-5a81-11e8-9d7f-aed4c1eb3eb0.png)

3.run project cleanup
![image](https://user-images.githubusercontent.com/18171453/40212176-41406a1c-5a81-11e8-9049-50380af3478c.png)

4. the added whitespace still there
![image](https://user-images.githubusercontent.com/18171453/40212217-85d902b0-5a81-11e8-854e-607cadecd162.png)

**Comment by Pnalson** [comment]
![image](https://user-images.githubusercontent.com/18171453/40218572-5a1e2c9a-5aa4-11e8-8116-e262fe5a2539.png)

**Comment by maybeec** [comment]
:+1: thanks. We will have a look at it. However, my time is very very limited until end of June.
So maybe one of my colleagues can help here.

**Comment by postmann** [comment]
@Pnalson, can you check if my commit fixed the issue? Just use http://www.agilereview.org/development_update to install from our CI build.

**Comment by Pnalson** [comment]
@postmann ，I have checked this bug after your commit。
![image](https://user-images.githubusercontent.com/18171453/41075684-63eb7a74-6a40-11e8-9cb0-845937ee575c.png)

I have noticed that whitespaces before comments all could be deleted，becase you use “\\s+”，But when add a comment agilereview just add one whitesace, this could change the origin reviewed files.
Why not just delet the  one whitespace added befor a comment.

**Comment by postmann** [comment]
Great, I'll release v0.9.3 once #26 is fixed as well.
