### ISSUE TITLE
How to get source from agileReview.author.jar

### ISSUE THREAD

**Issue by BiggyBrawn** [AgileReview-Project/AgileReview-Legacy-Plugin#32]
Hi, 
I would like to add new attributes in the Comment class, but these class is stored in a jar lib: agileReview.author.jar

May you share me the source code of this jar?

Thank you in advance,

Regards,
Biggy

**Comment by postmann** [comment]
These jar files are generated via xmlbeans from the xsd files. You have to change the xsd and then regenerate the jar files.

**Comment by BiggyBrawn** [comment]
Yep, i did that

Thanks a lot

Biggy
